// Code generated by mockery. DO NOT EDIT.

package source

import (
	bundle "github.com/perdasilva/rv1/internal/bundle"
	mock "github.com/stretchr/testify/mock"
)

// MockBundleSource is an autogenerated mock type for the BundleSource type
type MockBundleSource struct {
	mock.Mock
}

type MockBundleSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBundleSource) EXPECT() *MockBundleSource_Expecter {
	return &MockBundleSource_Expecter{mock: &_m.Mock}
}

// GetBundle provides a mock function with no fields
func (_m *MockBundleSource) GetBundle() (bundle.RegistryV1, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBundle")
	}

	var r0 bundle.RegistryV1
	var r1 error
	if rf, ok := ret.Get(0).(func() (bundle.RegistryV1, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bundle.RegistryV1); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bundle.RegistryV1)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBundleSource_GetBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBundle'
type MockBundleSource_GetBundle_Call struct {
	*mock.Call
}

// GetBundle is a helper method to define mock.On call
func (_e *MockBundleSource_Expecter) GetBundle() *MockBundleSource_GetBundle_Call {
	return &MockBundleSource_GetBundle_Call{Call: _e.mock.On("GetBundle")}
}

func (_c *MockBundleSource_GetBundle_Call) Run(run func()) *MockBundleSource_GetBundle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBundleSource_GetBundle_Call) Return(_a0 bundle.RegistryV1, _a1 error) *MockBundleSource_GetBundle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBundleSource_GetBundle_Call) RunAndReturn(run func() (bundle.RegistryV1, error)) *MockBundleSource_GetBundle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBundleSource creates a new instance of MockBundleSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBundleSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBundleSource {
	mock := &MockBundleSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
