// Code generated by mockery. DO NOT EDIT.

package certproviders

import (
	mock "github.com/stretchr/testify/mock"
	client "sigs.k8s.io/controller-runtime/pkg/client"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// MockCertificateProvider is an autogenerated mock type for the CertificateProvider type
type MockCertificateProvider struct {
	mock.Mock
}

type MockCertificateProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCertificateProvider) EXPECT() *MockCertificateProvider_Expecter {
	return &MockCertificateProvider_Expecter{mock: &_m.Mock}
}

// AdditionalObjects provides a mock function with given fields: cfg
func (_m *MockCertificateProvider) AdditionalObjects(cfg CertificateProvisionerConfig) ([]unstructured.Unstructured, error) {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for AdditionalObjects")
	}

	var r0 []unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(CertificateProvisionerConfig) ([]unstructured.Unstructured, error)); ok {
		return rf(cfg)
	}
	if rf, ok := ret.Get(0).(func(CertificateProvisionerConfig) []unstructured.Unstructured); ok {
		r0 = rf(cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(CertificateProvisionerConfig) error); ok {
		r1 = rf(cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateProvider_AdditionalObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdditionalObjects'
type MockCertificateProvider_AdditionalObjects_Call struct {
	*mock.Call
}

// AdditionalObjects is a helper method to define mock.On call
//   - cfg CertificateProvisionerConfig
func (_e *MockCertificateProvider_Expecter) AdditionalObjects(cfg interface{}) *MockCertificateProvider_AdditionalObjects_Call {
	return &MockCertificateProvider_AdditionalObjects_Call{Call: _e.mock.On("AdditionalObjects", cfg)}
}

func (_c *MockCertificateProvider_AdditionalObjects_Call) Run(run func(cfg CertificateProvisionerConfig)) *MockCertificateProvider_AdditionalObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(CertificateProvisionerConfig))
	})
	return _c
}

func (_c *MockCertificateProvider_AdditionalObjects_Call) Return(_a0 []unstructured.Unstructured, _a1 error) *MockCertificateProvider_AdditionalObjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateProvider_AdditionalObjects_Call) RunAndReturn(run func(CertificateProvisionerConfig) ([]unstructured.Unstructured, error)) *MockCertificateProvider_AdditionalObjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertSecretInfo provides a mock function with given fields: cfg
func (_m *MockCertificateProvider) GetCertSecretInfo(cfg CertificateProvisionerConfig) CertSecretInfo {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for GetCertSecretInfo")
	}

	var r0 CertSecretInfo
	if rf, ok := ret.Get(0).(func(CertificateProvisionerConfig) CertSecretInfo); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Get(0).(CertSecretInfo)
	}

	return r0
}

// MockCertificateProvider_GetCertSecretInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertSecretInfo'
type MockCertificateProvider_GetCertSecretInfo_Call struct {
	*mock.Call
}

// GetCertSecretInfo is a helper method to define mock.On call
//   - cfg CertificateProvisionerConfig
func (_e *MockCertificateProvider_Expecter) GetCertSecretInfo(cfg interface{}) *MockCertificateProvider_GetCertSecretInfo_Call {
	return &MockCertificateProvider_GetCertSecretInfo_Call{Call: _e.mock.On("GetCertSecretInfo", cfg)}
}

func (_c *MockCertificateProvider_GetCertSecretInfo_Call) Run(run func(cfg CertificateProvisionerConfig)) *MockCertificateProvider_GetCertSecretInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(CertificateProvisionerConfig))
	})
	return _c
}

func (_c *MockCertificateProvider_GetCertSecretInfo_Call) Return(_a0 CertSecretInfo) *MockCertificateProvider_GetCertSecretInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateProvider_GetCertSecretInfo_Call) RunAndReturn(run func(CertificateProvisionerConfig) CertSecretInfo) *MockCertificateProvider_GetCertSecretInfo_Call {
	_c.Call.Return(run)
	return _c
}

// InjectCABundle provides a mock function with given fields: obj, cfg
func (_m *MockCertificateProvider) InjectCABundle(obj client.Object, cfg CertificateProvisionerConfig) error {
	ret := _m.Called(obj, cfg)

	if len(ret) == 0 {
		panic("no return value specified for InjectCABundle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(client.Object, CertificateProvisionerConfig) error); ok {
		r0 = rf(obj, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateProvider_InjectCABundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InjectCABundle'
type MockCertificateProvider_InjectCABundle_Call struct {
	*mock.Call
}

// InjectCABundle is a helper method to define mock.On call
//   - obj client.Object
//   - cfg CertificateProvisionerConfig
func (_e *MockCertificateProvider_Expecter) InjectCABundle(obj interface{}, cfg interface{}) *MockCertificateProvider_InjectCABundle_Call {
	return &MockCertificateProvider_InjectCABundle_Call{Call: _e.mock.On("InjectCABundle", obj, cfg)}
}

func (_c *MockCertificateProvider_InjectCABundle_Call) Run(run func(obj client.Object, cfg CertificateProvisionerConfig)) *MockCertificateProvider_InjectCABundle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(client.Object), args[1].(CertificateProvisionerConfig))
	})
	return _c
}

func (_c *MockCertificateProvider_InjectCABundle_Call) Return(_a0 error) *MockCertificateProvider_InjectCABundle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateProvider_InjectCABundle_Call) RunAndReturn(run func(client.Object, CertificateProvisionerConfig) error) *MockCertificateProvider_InjectCABundle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCertificateProvider creates a new instance of MockCertificateProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCertificateProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCertificateProvider {
	mock := &MockCertificateProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
